CREATE TABLE
    IF NOT EXISTS APP.SPENDING_CATEGORY (
        SPENDING_CATEGORY_ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT "Primary Key for SPENDING_CATEGORY in this table",
        NAME VARCHAR(64) NOT NULL COMMENT "Name of the category",
        S3_KEY VARCHAR(512) NULL COMMENT "Key name of SVG in S3",
        IS_ACTIVE CHAR(1) NOT NULL DEFAULT "Y" COMMENT "Indicates if SPENDING_CATEGORY is active. N is No, Y is Yes",
        CREATED_BY BIGINT UNSIGNED NOT NULL DEFAULT 1 COMMENT "ID of who/what created this record",
        CREATED_ON DATETIME (0) NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT "Datetime of creation",
        LAST_MODIFIED_BY BIGINT UNSIGNED NOT NULL DEFAULT 1 COMMENT "ID of who/what updated this record",
        LAST_MODIFIED_ON DATETIME (0) NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT "Datetime of last time the record was updated",
        OPTIMISTIC_LOCK BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT "Optimistic lock for the record",
        PRIMARY KEY (SPENDING_CATEGORY_ID),
        INDEX IDX_NAME (NAME),
        INDEX IDX_IS_ACTIVE (IS_ACTIVE)
    ) ENGINE = InnoDB;