CREATE TABLE
    IF NOT EXISTS APP.SPENDING (
        SPENDING_ID UNSIGNED BIGINT NOT NULL AUTO_INCREMENT COMMENT "Primary key of this SPENDING record",
        SPENDING_USER_AGGR_ID UNSIGNED BIGINT NOT NULL COMMENT "Foreign key to the SPENDING_USER_AGGR that is associated with this SPENDING record",
        CATEGORY VARCHAR(100) NOT NULL "Category of the spending",
        AMOUNT DECIMAL(10, 2) NOT NULL COMMENT "Spending amount",
        CREATED_BY UNSIGNED BIGINT DEFAULT 1 COMMENT "ID of who/what created this record",
        CREATED_ON DATETIME (0) DEFAULT CURRENT_TIMESTAMP COMMENT "Datetime of creation",
        LAST_MODIFIED_BY UNSIGNED BIGINT DEFAULT 1 COMMENT "ID of who/what updated this record",
        LAST_MODIFIED_ON DATETIME (0) DEFAULT CURRENT_TIMESTAMP COMMENT "Datetime of last time the record was updated",
        OPTIMISTIC_LOCK UNSIGNED BIGINT DEFAULT 0 COMMENT "Optimistic lock for the record",
        PRIMARY KEY (SPENDING_ID),
        FOREIGN KEY (SPENDING_USER_AGGR_ID) REFERENCES APP.SPENDING_USER_AGGR (SPENDING_USER_AGGR_ID)
    ) ENGINE = InnoDB;