INSERT INTO APP.USER ( USER_ID, USERNAME, PASSWORD ) VALUES ( 1, "TEST1", "$2a$10$BY4NVSwVtxcZIOfca3yxye4871pe04J6PeDaNwaMB7/3JifPI6512" ) ; 
INSERT INTO APP.USER ( USER_ID, USERNAME, PASSWORD ) VALUES ( 2, "TEST2", "$2a$10$8icADGqRtWvXu6.WblPcEOwouXSpWh3V9ElOqRJ8Djd1E9fG78UX" ) ; 
INSERT INTO APP.USER ( USER_ID, USERNAME, PASSWORD ) VALUES ( 3, "TEST3", "$2a$10$kH0EPJSEfUDA1YwXNI7z/O6rzruDTnjsj7734N7VBo4YLpEGY1eC." ) ; 
INSERT INTO APP.USER ( USER_ID, USERNAME, PASSWORD ) VALUES ( 4, "TEST4", "$2a$10$DiaBi8Ry3Z.S1DZJUzYw/eTYh.aNMcA07oxxYJJthXDirxrci.M/W" ) ; 
INSERT INTO APP.USER ( USER_ID, USERNAME, PASSWORD ) VALUES ( 5, "TEST5", "$2a$10$SmxnSx2wqIP.Dopz6zYInudBT1Lbu0opFrq.zyQM1KQogijssvNNi" ) ; 