
CREATE TEMPORARY TABLE APP.CATEGORY (
    CATEGORY_ID         BIGINT UNSIGNED         AUTO_INCREMENT,
    CATEGORY            VARCHAR(100),

    PRIMARY KEY ( CATEGORY_ID )
);

INSERT INTO APP.CATEGORY ( CATEGORY ) VALUES ( "Automotive" );
INSERT INTO APP.CATEGORY ( CATEGORY ) VALUES ( "Bills" );
INSERT INTO APP.CATEGORY ( CATEGORY ) VALUES ( "Baby" );
INSERT INTO APP.CATEGORY ( CATEGORY ) VALUES ( "Beauty" );
INSERT INTO APP.CATEGORY ( CATEGORY ) VALUES ( "Books" );
INSERT INTO APP.CATEGORY ( CATEGORY ) VALUES ( "Clothing" );
INSERT INTO APP.CATEGORY ( CATEGORY ) VALUES ( "Computers" );
INSERT INTO APP.CATEGORY ( CATEGORY ) VALUES ( "Electronics" );
INSERT INTO APP.CATEGORY ( CATEGORY ) VALUES ( "Food" );
INSERT INTO APP.CATEGORY ( CATEGORY ) VALUES ( "Games" );
INSERT INTO APP.CATEGORY ( CATEGORY ) VALUES ( "Garden" );
INSERT INTO APP.CATEGORY ( CATEGORY ) VALUES ( "Grocery" );
INSERT INTO APP.CATEGORY ( CATEGORY ) VALUES ( "Health" );
INSERT INTO APP.CATEGORY ( CATEGORY ) VALUES ( "Home" );
INSERT INTO APP.CATEGORY ( CATEGORY ) VALUES ( "Industrial" );
INSERT INTO APP.CATEGORY ( CATEGORY ) VALUES ( "Jewelry" );
INSERT INTO APP.CATEGORY ( CATEGORY ) VALUES ( "Kids" );
INSERT INTO APP.CATEGORY ( CATEGORY ) VALUES ( "Movies" );
INSERT INTO APP.CATEGORY ( CATEGORY ) VALUES ( "Music" );
INSERT INTO APP.CATEGORY ( CATEGORY ) VALUES ( "Outdoors" );
INSERT INTO APP.CATEGORY ( CATEGORY ) VALUES ( "Pet" );
INSERT INTO APP.CATEGORY ( CATEGORY ) VALUES ( "Shoes" );
INSERT INTO APP.CATEGORY ( CATEGORY ) VALUES ( "Sports" );
INSERT INTO APP.CATEGORY ( CATEGORY ) VALUES ( "Tools" );
INSERT INTO APP.CATEGORY ( CATEGORY ) VALUES ( "Toys" );

DELIMITER $$

CREATE PROCEDURE APP.APP_ADD_SPENDINGS ( userId BIGINT )
BEGIN
    DECLARE I INT;
    DECLARE J INT;

    SET I = 0;
    
    INSERT_SPENDING_DATE_LOOP: LOOP
        IF I = 10 THEN
            LEAVE INSERT_SPENDING_DATE_LOOP;
        END IF;

        INSERT INTO APP.SPENDING_USER_AGGR ( USER_ID, DATE ) VALUES (userId, DATE_SUB(CURDATE(), INTERVAL FLOOR(RAND() * 10000) DAY));

        SET J = 0;
        INSERT_SPENDING_LOOP: LOOP
            IF J = 10 THEN
                LEAVE INSERT_SPENDING_LOOP;
            END IF;

            INSERT INTO APP.SPENDING ( SPENDING_USER_AGGR_ID, CATEGORY, AMOUNT ) SELECT MAX(SUA.SPENDING_USER_AGGR_ID), ( SELECT CATEGORY FROM APP.CATEGORY ORDER BY RAND() LIMIT 1 ), RAND() * 100000 FROM APP.SPENDING_USER_AGGR SUA ;

            SET J = J + 1;
            ITERATE INSERT_SPENDING_LOOP;
        END LOOP INSERT_SPENDING_LOOP;

        SET I = I + 1;
        ITERATE INSERT_SPENDING_DATE_LOOP;
    END LOOP INSERT_SPENDING_DATE_LOOP;
END $$

DELIMITER ;

CALL APP.APP_ADD_SPENDINGS (1);
CALL APP.APP_ADD_SPENDINGS (2);
CALL APP.APP_ADD_SPENDINGS (3);
CALL APP.APP_ADD_SPENDINGS (4);
CALL APP.APP_ADD_SPENDINGS (5);

DROP TEMPORARY TABLE APP.CATEGORY;
DROP PROCEDURE IF EXISTS APP.APP_ADD_SPENDINGS;