CREATE TABLE
    IF NOT EXISTS APP.SPENDING (
        SPENDING_ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT "Primary key of this SPENDING record",
        SPENDING_USER_AGGR_ID BIGINT UNSIGNED NOT NULL COMMENT "Foreign key to the SPENDING_USER_AGGR that is associated with this SPENDING record",
        SPENDING_CATEGORY_ID BIGINT UNSIGNED NOT NULL COMMENT "Foreign key to SPENDING_CATEGORY that this SPENDING pertains to",
        AMOUNT DECIMAL(10, 2) NOT NULL COMMENT "Spending amount",
        CREATED_BY BIGINT UNSIGNED NOT NULL DEFAULT 1 COMMENT "ID of who/what created this record",
        CREATED_ON DATETIME (0) NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT "Datetime of creation",
        LAST_MODIFIED_BY BIGINT UNSIGNED NOT NULL DEFAULT 1 COMMENT "ID of who/what updated this record",
        LAST_MODIFIED_ON DATETIME (0) NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT "Datetime of last time the record was updated",
        OPTIMISTIC_LOCK BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT "Optimistic lock for the record",
        PRIMARY KEY (SPENDING_ID),
        FOREIGN KEY (SPENDING_USER_AGGR_ID) REFERENCES APP.SPENDING_USER_AGGR (SPENDING_USER_AGGR_ID),
        FOREIGN KEY (SPENDING_CATEGORY_ID) REFERENCES APP.SPENDING_CATEGORY (SPENDING_CATEGORY_ID)
    ) ENGINE = InnoDB DEFAULT CHARSET = utf8 COLLATE = utf8mb4_bin;