INSERT INTO APP.USER (USER_ID, EMAIL, USERNAME, IS_VERIFIED, PASSWORD) VALUES ( 1001, "test1@test.com", "TEST1", "Y", "$2a$10$BY4NVSwVtxcZIOfca3yxye4871pe04J6PeDaNwaMB7/3JifPI6512" );
INSERT INTO APP.USER (USER_ID, EMAIL, USERNAME, IS_VERIFIED, PASSWORD) VALUES ( 1002, "test2@test.com", "TEST2", "Y", "$2a$10$8icADGqRtWvXu6.WblPcEOwouXSpWh3V9ElOqRJ8Djd1E9fG78UX" );
INSERT INTO APP.USER (USER_ID, EMAIL, USERNAME, IS_VERIFIED, PASSWORD) VALUES ( 1003, "test3@test.com", "TEST3", "Y", "$2a$10$kH0EPJSEfUDA1YwXNI7z/O6rzruDTnjsj7734N7VBo4YLpEGY1eC." );
INSERT INTO APP.USER (USER_ID, EMAIL, USERNAME, IS_VERIFIED, PASSWORD) VALUES ( 1004, "test4@test.com", "TEST4", "Y", "$2a$10$DiaBi8Ry3Z.S1DZJUzYw/eTYh.aNMcA07oxxYJJthXDirxrci.M/W" );
INSERT INTO APP.USER (USER_ID, EMAIL, USERNAME, IS_VERIFIED, PASSWORD) VALUES ( 1005, "test5@test.com", "TEST5", "Y", "$2a$10$SmxnSx2wqIP.Dopz6zYInudBT1Lbu0opFrq.zyQM1KQogijssvNNi" );
INSERT INTO APP.USER (USER_ID, EMAIL, USERNAME, IS_VERIFIED, PASSWORD) VALUES ( 1006, "test6@test.com", "TEST6", "Y", "$2a$12$ezT7yVPT9xdbcTYc8r54lODWzRrzdGID6lpH3NS63t8izNRZ2g3Hq" );
INSERT INTO APP.USER (USER_ID, EMAIL, USERNAME, IS_VERIFIED, PASSWORD) VALUES ( 1007, "test7@test.com", "TEST7", "Y", "$2a$12$Dkp7aP2ivSW.q3090uE9i.vDai6WCxJxkHCzcoT78p4tPw72NzYuC" );
INSERT INTO APP.USER (USER_ID, EMAIL, USERNAME, IS_VERIFIED, PASSWORD) VALUES ( 1008, "test8@test.com", "TEST8", "Y", "$2a$12$3eX2cCdIxFCSSAgabQ1C5.2i/GHLEbboEiBZt0vde582sWukGJ6AG" );
INSERT INTO APP.USER (USER_ID, EMAIL, USERNAME, IS_VERIFIED, PASSWORD) VALUES ( 1009, "test9@test.com", "TEST9", "Y", "$2a$12$jfziKfPyeVK5Uo5fGf1Adu8KG1.RxLLAoTtjZYBNBeGDa/oj2Un/y" );
INSERT INTO APP.USER (USER_ID, EMAIL, USERNAME, IS_VERIFIED, PASSWORD) VALUES ( 1010, "test0@test.com", "TEST10", "Y", "$2a$12$HYwRE6Ixt4J5xYw0RZOEheSyrcaFVAfdMy80CemxFhiIFTjFfZh1u" );

COMMIT;