INSERT INTO
    APP.SPENDING_CATEGORY (NAME)
VALUES
    ("Transporation");

INSERT INTO
    APP.SPENDING_CATEGORY (NAME)
VALUES
    ("Clothing");

INSERT INTO
    APP.SPENDING_CATEGORY (NAME)
VALUES
    ("Vehicle");

INSERT INTO
    APP.SPENDING_CATEGORY (NAME)
VALUES
    ("Travel");

INSERT INTO
    APP.SPENDING_CATEGORY (NAME)
VALUES
    ("Health");

INSERT INTO
    APP.SPENDING_CATEGORY (NAME)
VALUES
    ("Food");

INSERT INTO
    APP.SPENDING_CATEGORY (NAME)
VALUES
    ("Pet");

INSERT INTO
    APP.SPENDING_CATEGORY (NAME)
VALUES
    ("Entertainment");

INSERT INTO
    APP.SPENDING_CATEGORY (NAME)
VALUES
    ("Utility");

INSERT INTO
    APP.SPENDING_CATEGORY (NAME)
VALUES
    ("Subscription");

INSERT INTO
    APP.SPENDING_CATEGORY (NAME)
VALUES
    ("Savings");

INSERT INTO
    APP.SPENDING_CATEGORY (NAME)
VALUES
    ("Other");