DELIMITER $$

CREATE PROCEDURE APP.APP_ADD_SPENDINGS ( userId BIGINT )
BEGIN
    DECLARE I INT;
    DECLARE J INT;

    SET I = 0;
    
    INSERT_SPENDING_DATE_LOOP: LOOP
        IF I = 100 THEN
            LEAVE INSERT_SPENDING_DATE_LOOP;
        END IF;

        INSERT INTO
            APP.SPENDING_USER_AGGR (USER_ID, DATE)
        VALUES
            (
                userId,
                DATE_SUB(CURDATE(), INTERVAL FLOOR(RAND() * 10000) DAY)
            );

        INSERT INTO
            APP.SPENDING (SPENDING_USER_AGGR_ID, SPENDING_CATEGORY_ID, AMOUNT)
        SELECT
            (
                SELECT
                    MAX(SUA.SPENDING_USER_AGGR_ID)
                FROM
                    APP.SPENDING_USER_AGGR SUA
            ),
            SC.SPENDING_CATEGORY_ID,
            RAND () * 100000
        FROM
            APP.SPENDING_CATEGORY SC;


        SET I = I + 1;
        ITERATE INSERT_SPENDING_DATE_LOOP;
    END LOOP INSERT_SPENDING_DATE_LOOP;
END $$

DELIMITER ;

CALL APP.APP_ADD_SPENDINGS (1001);
CALL APP.APP_ADD_SPENDINGS (1002);
CALL APP.APP_ADD_SPENDINGS (1003);
CALL APP.APP_ADD_SPENDINGS (1004);
CALL APP.APP_ADD_SPENDINGS (1005);

DROP PROCEDURE IF EXISTS APP.APP_ADD_SPENDINGS;