version: "3.8"
services:
  database:
    container_name: MySQL-Database
    build: ../database/
    volumes:
      - db-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    healthcheck:
      test: mysql --user=root --password=$$MYSQL_ROOT_PASSWORD -e 'SELECT 1 FROM APP.SPENDING LIMIT 1'
      interval: 1m
      timeout: 30s
      retries: 7
      start_period: 30s
  backend:
    container_name: Spring-Backend
    build: 
      context: ../backend/
    volumes:
      - ../backend:/backend:rw
    environment:
      - MYSQL_HOST=database
      - ENV=${MODE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
    ports:
      - "8080:8080"
      - "5005:5005"
    depends_on:
      database:
        condition: service_healthy
    restart: always
  frontend:
    container_name: React-Frontend
    build:
      context: ../frontend/
    volumes:
      - ../frontend/src:/frontend/src
    environment:
      - MODE=${MODE}
    ports:
      - "5173:5173"
    depends_on:
      - "backend"

volumes:
  db-data: {}
