version: "3.8"
services:
  database:
    container_name: MySQL-Database
    build: ../database/
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"
  backend:
    container_name: Spring-Backend
    build: ../backend/
    volumes:
      - ../backend:/backend:rw
    environment:
      - MYSQL_HOST=database
    ports:
      - "8080:8080"
      - "5005:5005"
    depends_on:
      - "database"
  frontend:
    container_name: React-Frontend
    build: ../frontend/
    volumes:
      - ../frontend/src:/frontend/src
    ports:
      - "5173:5173"
    depends_on:
      - "backend"

volumes:
  db-data: {}