--- # Applies to all profiles/envs
spring:
  mvc:
    format:
      date: yyyy-MM-dd
  jackson:
    date-format: yyyy-MM-dd
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    generate-ddl: false
    open-in-view: true
springdoc.api-docs.enabled: false
server:
  port: 8080
ses:
  template:
    name:
      registration-email: RegistrationEmail
      password-reset-email: PasswordResetEmail
  from-email: spendingstracker.no.reply@gmail.com
s3:
  presigned-url-expiration-minutes: 10
classpath-resources:
  sql-resources:
    - /sql/findSpendingsForBarChart.sql
    - /sql/findSpendingsForLineChart.sql
    - /sql/countSpendingsForLineChart.sql
    - /sql/countSpendingsForBarChart.sql
--- # Local Profile
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/APP
    username: root
    password: ${MYSQL_ROOT_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
  devtools:
    remote:
      secret: mysecret
    restart:
      poll-interval: 2s
      quiet-period: 1s
      enabled: true
springdoc.api-docs.enabled: true
jwt:
  secret-key-path: classpath:/secrets/secret-key.key
cors:
  allowed-origins: http://localhost:5173, http://127.0.0.1:5173
logging:
  level:
    org:
      springframework:
        security: TRACE
    com.spendingstracker: DEBUG
redirects:
  verify-acct: http://localhost:5173/verify-acct?
  password-reset: http://localhost:5173/password-reset?
google:
  client-id: ${GOOGLE_CLIENT_ID}
s3:
  categories-bucket-name: spending-categories-svg