version: "3.8"
services:
  spendings-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - db-data:/var/lib/mysql
      - ./:/docker-entrypoint-initdb.d/
    ports:
      - "3306:3306"

volumes:
  db-data: {}